### ISSUE TITLE
[Forge] Profiler "Running for:" timer displays the wrong time

### ISSUE THREAD

**Issue by NeOObsidian** [tasgon/observable#2] opened 2021-07-31 12:08 UTC
**Issue:** When running the profiler, the "Running for" timer displays the wrong time, no matter what length of time you set. This is only a visual bug, as the profiler correctly runs for the time you set.

**Forge/Fabric:** Forge

**Modpack:** All The Mods 6, with extra mods added.

**Modlist:** https://pastebin.com/LGXGzEEc

**Screenshot:**  
![javaw 2021-07-31 13-04-55-385](https://user-images.githubusercontent.com/25354257/127739390-76a59e0a-5aaa-4276-8140-8e7a4bc99c7b.png)

**Comment by tasgon** [comment] 2021-07-31 20:46
I'm unable to reproduce with base ATM6. Could you give me a more concise list of the mods added on top?

**Comment by NeOObsidian** [comment] 2021-07-31 21:50
Certainly! The mods added on top can be found in the link below:

https://pastebin.com/9XbX5QR2

I did also change the hotkey for this mod, but I doubt that has any bearing.

Thanks for the great mod!

**Comment by Quezler** [comment] 2021-08-13 17:24
same issue in enigmatica 6 0.5.9

**Comment by tasgon** [comment] 2021-08-14 11:24
@Quezler did you make any alterations to the pack, and could you share the client log files (and server log too, if you have access)? Also, does the bug happen every time?

**Comment by Quezler** [comment] 2021-08-14 11:48
in the terms of adding or removing mods this is the only alteration, and i'd rather not send the entire client & server log over for chat privacy reasons, but yes it does happen every time, i did however notice this:

![Screen Shot 2021-08-14 at 13 43 04](https://user-images.githubusercontent.com/3179271/129445216-fb256ff7-fcde-42b6-9854-19bff6632204.png)

![Screen Shot 2021-08-14 at 13 43 40](https://user-images.githubusercontent.com/3179271/129445227-d6284ef2-437c-427c-be53-1393c87375dc.png)

for me it seems prefixed by 999033 something ontop of the 30 seconds each time, notably a different number than the top pic in this thread (999033 as in: once it reaches this number it finishes, so when it starts its ~30 seconds more)

if you have any specific part of the server/client log you'd like to see do let me know and i'll copy paste just those bits.

i am on a mac btw 🍎

**Comment by tasgon** [comment] 2021-08-14 19:41
What OS/architecture does the server have?

**Comment by tasgon** [comment] 2021-08-15 03:21
Just pushed a potential fix, let me know if it solves your problem.

**Comment by Quezler** [comment] 2021-08-15 06:04
> What OS/architecture does the server have?

Ubuntu

> Just pushed a potential fix, let me know if it solves your problem.

I'll give it a shot 👍

**Comment by Quezler** [comment] 2021-08-15 08:02
it did! (though strangely on singleplayer it seemed to use a , and on multiplayer a . (but that might have been the modpack))

**Comment by Quezler** [comment] 2021-08-15 08:03
@NeOObsidian does the 0.1.2 version fix the issue for you as well?

**Comment by tasgon** [comment] 2021-08-15 16:34
> it did!

Gonna close this for now, then. If the other guy (or anyone else) is still having this problem, they can reopen the issue.

**Closed by tasgon** 2021-08-15 16:34 UTC
