### ISSUE TITLE
Crash on 1.20.1 Allthemods 9 

### ISSUE THREAD

**Issue by Epihuani** [tasgon/observable#84] opened 2024-03-29 06:01 UTC
[crash-2024-03-28_22.48.32-server.txt](https://github.com/tasgon/observable/files/14800260/crash-2024-03-28_22.48.32-server.txt)
Crash report for what happened: I wasn't logged into the server, so I am unsure what could've caused it outside of the crash report.

**Comment by tasgon** [comment] 2024-03-29 06:32
What makes you think this has anything to do with Observable? Looking at the crash report, it seems to be a fairly standard server hang.

**Comment by Epihuani** [comment] 2024-03-29 08:27
Apologies, wrong crash report 
[crash-2024-03-28_22.45.30-server.txt](https://github.com/tasgon/observable/files/14801562/crash-2024-03-28_22.45.30-server.txt)

**Comment by tasgon** [comment] 2024-03-29 23:22
Are you able to reproduce the error? Due to the nature of Observable, Forge will always suspect it whenever a crash happens involving an entity, even if the mod has nothing to do with the crash.

**Comment by CaspyBXL** [comment] 2024-04-02 16:46
Hello I'm using "Chosen's modded Adventure" Modpack
And I have a similar error
here is my Crash Report to compare
[crash-2024-04-02_16.02.26-server.txt](https://github.com/tasgon/observable/files/14841206/crash-2024-04-02_16.02.26-server.txt)
As you can see its also a Wither Skeleton that is the issue in the Entity and the suspected mod is also "Observable"
I'm not sure 100% if "Observable" is the issue but I thought I would at least post it here since someone with a complete different modpack has the same issues in the logs.

Edit : Also on version 1.20.1

**Comment by CaspyBXL** [comment] 2024-04-03 10:42
Update on this issue :
For everyone who has this error
-> removeErroringEntities = true  can be set in forge-server.toml inside the world/serverconfig/ 
Anwser provided by Miles from the Chosen Mod Discord !
It comes from the mod called |attributefix|

So for me you can disregard this. I hope this helps too for you @returnofnothing !

**Comment by tasgon** [comment] 2024-09-01 02:21
This doesn't look like it's being caused by Observable, closing

**Closed as not planned by tasgon** 2024-09-01 02:21 UTC
