### ISSUE TITLE
Crash with the star wars the block wars mod.

### ISSUE THREAD

**Issue by BichoMESP** [tasgon/observable#75] opened 2024-01-01 17:40 UTC
Crash with the star wars the block wars mod.
[crash-2024-01-01_11.31.10-server.txt](https://github.com/tasgon/observable/files/13805446/crash-2024-01-01_11.31.10-server.txt)
I've also sent it to the creator of the Star Wars The Block Wars mod.

**Comment by tasgon** [comment] 2024-02-03 10:40
I doubt this has anything to do with the crash. Because Observable wraps every entity tick function, it may look like it's the cause of an issue, when usually it will be due to the function being wrapped (in this case, the Star Wars mod). Closing for now, but if you find evidence that my mod is at fault here, feel free to reopen the issue.

**Closed as not planned by tasgon** 2024-02-03 10:40 UTC
