### ISSUE TITLE
Update to 1.20+

### ISSUE THREAD

**Issue by SilverScythe64** [tasgon/observable#60] opened 2023-07-26 04:14 UTC
Hello.

Your mod is very useful.
I cannot speak on behalf of all servers, but at least in regard to our own servers, your mod is extremely important to us.

We hope to see you continue the development of this great utility mod, for current and future versions of Minecraft!

**Comment by tasgon** [comment] 2023-07-27 05:21
Duplicate of #58. I'm planning to tackle it fairly soon.

**Closed as not planned by tasgon** 2023-07-27 05:21 UTC
